CREATE TABLE saferes_guest (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    phone_number TEXT NOT NULL,
    guest_name TEXT NOT NULL,
    date_added TIMESTAMP DEFAULT now() NOT NULL,
    times_visited INTEGER DEFAULT 0,
    last_visit TIMESTAMP DEFAULT now() NOT NULL,
    restaurant_id INTEGER REFERENCES safeRes_restaurant(id)
)