CREATE TABLE saferes_guest (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    restaurant_id INTEGER REFERENCES safeRes_restaurant(id),
    phone_number TEXT NOT NULL,
    guest_name TEXT NOT NULL,
    times_visited INTEGER DEFAULT 0,
    no_shows INTEGER DEFAULT 0,
    cancellations INTEGER DEFAULT 0,
    date_added TIMESTAMP DEFAULT now() NOT NULL,
    last_visit TEXT
);